// <auto-generated />
namespace ImagePicker.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class addPhoneandImagetable : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addPhoneandImagetable));
        
        string IMigrationMetadata.Id
        {
            get { return "201703230836305_add-Phone-and-Image-table"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
